version: '3'
services:
  web:
    container_name: todolist_php
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - db

  db:
    container_name: todolist_mySQL
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
    volumes: 
      - ./db/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql --default-authentication-plugin=mysql_native_password
    restart: always